#!/bin/sh

set -e

case "$1" in
    remove)
        update-alternatives --quiet --remove irc.protocol \
            /usr/share/kvirc/3.2.0/services/irc.protocol
        update-alternatives --quiet --remove irc6.protocol \
            /usr/share/kvirc/3.2.0/services/irc6.protocol
    ;;

    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0
