#ifndef _kvi_sysconfig_h_
#define _kvi_sysconfig_h_
//=============================================================================
//
// System dependant configuration for KVIrc
// This file is automatically generated: do not edit
//
//=============================================================================

#define KVI_SYSTEM_SIZE_OF_SHORT_INT ${CMAKE_SYSTEM_SIZE_OF_SHORT_INT}
#define KVI_SYSTEM_SIZE_OF_INT ${CMAKE_SYSTEM_SIZE_OF_INT}
#define KVI_SYSTEM_SIZE_OF_LONG_INT ${CMAKE_SYSTEM_SIZE_OF_LONG_INT}
#define KVI_SYSTEM_SIZE_OF_LONG_LONG_INT ${CMAKE_SYSTEM_SIZE_OF_LONG_LONG_INT}

#cmakedefine KVI_SYSTEM_HAS_SYS_TYPES_H 1
#cmakedefine KVI_SYSTEM_HAS_STRINGS_H 1

#cmakedefine KVI_COMPILE_USE_POSIXTHREADS 1
#cmakedefine KVI_COMPILE_USE_WIN32THREADS 1
#cmakedefine KVI_COMPILE_USE_SOLARISTHREADS 1

#cmakedefine KVI_COMPILE_X11_SUPPORT 1

#cmakedefine KVI_SYSTEM_IS_BIG_ENDIAN 1

#endif //!_kvi_sysconfig_h_
