#ifndef _kvi_sysbuildinfo_h_
#define _kvi_sysbuildinfo_h_
//=============================================================================
//
// System dependant configuration for KVIrc
// This file is automatically generated: do not edit
//
//=============================================================================

#define KVIRC_BUILD_DATE "${CMAKE_KVIRC_BUILD_DATE}"
#define KVIRC_BUILD_COMMAND "${CMAKE_KVIRC_BUILD_COMMAND}"
#define KVIRC_BUILD_FLAGS "${CMAKE_KVIRC_BUILD_FLAGS}"
#define KVIRC_BUILD_SYSTEM "${CMAKE_KVIRC_BUILD_SYSTEM}"
#define KVIRC_BUILD_SYSTEM_NAME "${CMAKE_KVIRC_BUILD_SYSTEM_NAME}"
#define KVIRC_BUILD_SYSTEM_VERSION "${CMAKE_KVIRC_BUILD_SYSTEM_VERSION}"
#define KVIRC_BUILD_CPU "${CMAKE_KVIRC_BUILD_CPU}"
#define KVIRC_BUILD_COMPILER "${CMAKE_KVIRC_BUILD_COMPILER}"
#define KVIRC_BUILD_COMPILER_FLAGS "${CMAKE_KVIRC_BUILD_COMPILER_FLAGS}"
#define KVIRC_BUILD_REVISION "${CMAKE_KVIRC_BUILD_REVISION}"

#endif //!_kvi_sysbuildinfo_h_
