#ifndef _kvi_sysbuildinfo_h_
#define _kvi_sysbuildinfo_h_
//=============================================================================
//
// System dependant configuration for KVIrc
// This file is automatically generated: do not edit
//
//=============================================================================

#define KVIRC_BUILD_DATE "${CMAKE_KVIRC_BUILD_DATE}"

#endif //!_kvi_sysbuildinfo_h_
